# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Aditya Singh
tagline:          ''
description:      'Technology Pantomath' #'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# url:              http://adityasin.ga
baseurl:          /

author:
  name:           'Aditya Singh'
  url:            https://www.linkedin.com/in/singhaditya8499/

paginate:         5

# Custom vars
version:          1.1.0

github:
  # repo:           https://github.com/poole/hyde

footer-links:
  dribbble:
  email: singh.aditya8499@gmail.com
  facebook: singh.aditya8499
  flickr:
  github: singhaditya8499
  instagram: asli_singham/
  linkedin: singhaditya8499/