# Site Configuration
baseURL = 'https://singhaditya8499.github.io/portfolio-site/'
languageCode = "en-us"
title = "Aditya's Portfolio"
theme = "PaperMod"
# googleAnalytics = "G-XXXXXXXXXX"
buildFuture = true

# Output Formats
[outputs]
  home = ['html', 'rss', 'json']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

# Site Parameters
[params]
  mainSections = ["blog", "musings", "vim_stuff"]
  hideSummary = true
  comments = true
  archives = true
  archiveSection = ["blog", "musings", "vim_stuff"]
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPageNums = true
  search = true
  searchPlaceholder = "Search..."
  disableScrollToTop = true


  # Home Page Information
  [params.homeInfoParams]
Title = "{{< terminal-prompt >}}"
Content = "### Hey! I'm Aditya\n Welcome to my corner of the internet. This website is my personal portfolio where I share projects, writing, and my learning journey."

  # Social Icons
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/singhaditya8499"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:your-email@example.com"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/your-handle"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/your-linkedin-id/"

  [[params.socialIcons]]
  name = "kaggle"
  url = "https://www.kaggle.com/your-kaggle-id"

  [[params.socialIcons]]
  name = "buymeacoffee"
  url = "https://buymeacoffee.com/your-id"

  [[params.socialIcons]]
  name = "RSS"
  url = "https://singhaditya8499.github.io/portfolio-site/index.xml"

  # Cover Image Parameters
  [params.cover]
  linkFullImages = true

  # Search Settings
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1_000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]

# Menu Configuration
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/blog/"
weight = 3

[[menu.main]]
identifier = "musings"
name = "Essays"
url = "/musings/"
weight = 4

[[menu.main]]
identifier = "vim_stuff"
name = "Vim Stuff"
url = "/vim_stuff/"
weight = 5

[[menu.main]]
identifier = "search"
name = "🔍"
url = "/search/"
weight = 6




# Markup and Syntax Highlighting Settings
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = false
  noClasses = false
